"""E18.1 general data: Qwen3-4B's OWN replies to general prompts (self-distillation), thinking on and off.

Purpose (NOTEBOOK 10-06): E18's thinking was trained only on our narrow task and turned every thought into the record
list (PersonaMem, thinking on: 98% of thoughts). Mixing the base model's own general behaviour into training keeps the
original thinking for questions that are not about dated values (cf. FILM-7B mixing ~11% general instruction data).
Nothing new is taught: prompts come from a public instruction mixture, replies are generated by the untouched base model.

Prompts: allenai/tulu-3-sft-mixture (ODC-BY; pinned revision below). Single-turn user prompts only, English-looking,
30-2000 characters. Excluded sources (keep the no-harm tests clean): anything whose source name mentions instruction
following / IFEval / GSM / MMLU / ARC / HellaSwag / LongBench, multilingual (aya) sets; and any prompt sharing an
8-gram with an IFEval prompt. Stratified over sources (equal cap per source).
Generation: half the prompts with thinking on (Qwen3 recommended thinking sampling T 0.6 / top-p 0.95 / top-k 20,
max 3072 new tokens), half with thinking off (Qwen3 recommended non-thinking sampling T 0.7 / top-p 0.8 / top-k 20,
max 1024). Kept only when the reply finished (thinking: closed </think>) and prompt + reply <= 6000 tokens.
usage: python gen_selfdistill.py --n 600 [--engine vllm|hf]  -> data_train/selfdistill_train.jsonl
"""
import argparse
import hashlib
import json
import random
import re

REPO, REV = "allenai/tulu-3-sft-mixture", "b14afda60f1bbebe55d5d2fa1e4df5042f97f8be"
SHARDS = [f"data/train-0000{i}-of-00006.parquet" for i in range(6)]
# 10-07 (cloud, user-approved, before any generation): "ifdata" (personahub_ifdata = instruction following) and
# "math-grade" (tulu-3-sft-personas-math-grade = grade-school math, GSM8K's domain) were not caught; added per the pre-registration text
EXCLUDE = re.compile(r"instruction.?following|ifeval|\bif[_-]|ifdata|gsm|math-grade|mmlu|\barc\b|hellaswag|longbench|aya", re.I)
THINK = dict(temperature=0.6, top_p=0.95, top_k=20, max_tokens=3072)
DIRECT = dict(temperature=0.7, top_p=0.8, top_k=20, max_tokens=1024)
MODEL = "Qwen/Qwen3-4B"


def ngrams(text, n=8):
    w = re.findall(r"[a-z0-9]+", text.lower())
    return {" ".join(w[i:i + n]) for i in range(len(w) - n + 1)}


def load_prompts(n, seed):
    import pandas as pd
    from huggingface_hub import hf_hub_download
    df = pd.concat([pd.read_parquet(hf_hub_download(REPO, f, repo_type="dataset", revision=REV),
                                    columns=["id", "messages", "source"]) for f in SHARDS], ignore_index=True)
    df = df[df.messages.map(lambda m: len(m) == 2 and m[0]["role"] == "user" and m[1]["role"] == "assistant")]
    df["prompt"] = df.messages.map(lambda m: m[0]["content"].strip())
    df = df[df.prompt.str.len().between(30, 2000) & ~df.source.str.contains(EXCLUDE)]
    df = df[df.prompt.map(lambda p: sum(c.isascii() for c in p) / len(p) > 0.97)]
    from datasets import load_dataset
    ife = set().union(*[ngrams(x["prompt"]) for x in load_dataset("google/IFEval", split="train")])
    df = df[df.prompt.map(lambda p: not (ngrams(p) & ife))]
    print("eligible prompts", len(df), "| sources", df.source.nunique())
    rng = random.Random(seed)
    groups = {s: g.sample(frac=1, random_state=seed) for s, g in df.groupby("source")}
    cap = max(1, -(-n // len(groups)))
    picked = []
    for s in sorted(groups):
        picked += groups[s].head(cap).to_dict("records")
    rng.shuffle(picked)
    return picked[:n]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=600)
    ap.add_argument("--seed", type=int, default=1818)
    ap.add_argument("--engine", default="vllm", choices=["vllm", "hf"])
    ap.add_argument("--out", default="data_train/selfdistill_train.jsonl")
    ap.add_argument("--model", default=MODEL, help="whose own replies (cloud 10-07: Qwen/Qwen3-8B for the 8B run)")
    args = ap.parse_args()
    from transformers import AutoTokenizer
    tok = AutoTokenizer.from_pretrained(args.model)
    items = load_prompts(args.n, args.seed)
    for i, it in enumerate(items):
        it["think"] = i % 2 == 0
        it["text"] = tok.apply_chat_template([{"role": "user", "content": it["prompt"]}], tokenize=False,
                                             add_generation_prompt=True, enable_thinking=it["think"])
    outs = []
    if args.engine == "vllm":
        from vllm import LLM, SamplingParams
        llm = LLM(args.model, dtype="bfloat16", max_model_len=8192, seed=args.seed)
        for mode, kw in ((True, THINK), (False, DIRECT)):
            batch = [it for it in items if it["think"] == mode]
            res = llm.generate([it["text"] for it in batch], SamplingParams(seed=args.seed, **kw))
            for it, r in zip(batch, res):
                o = r.outputs[0]
                outs.append((it, o.text, o.finish_reason == "stop"))
    else:
        import torch
        from transformers import AutoModelForCausalLM
        model = AutoModelForCausalLM.from_pretrained(args.model, dtype=torch.bfloat16, device_map="cuda").eval()
        for it in items:
            kw = THINK if it["think"] else DIRECT
            ids = tok(it["text"], return_tensors="pt", add_special_tokens=False).input_ids.cuda()
            torch.manual_seed(args.seed)
            with torch.no_grad():
                out = model.generate(ids, attention_mask=torch.ones_like(ids), do_sample=True, temperature=kw["temperature"],
                                     top_p=kw["top_p"], top_k=kw["top_k"], max_new_tokens=kw["max_tokens"])
            new = out[0, ids.shape[1]:]
            outs.append((it, tok.decode(new, skip_special_tokens=True), new[-1].item() in (tok.eos_token_id, tok.convert_tokens_to_ids("<|im_end|>"))))
    rows, drop = [], {"unfinished": 0, "too_long": 0}
    for it, text, done in outs:
        text = text.strip()
        if not done or (it["think"] and "</think>" not in text):
            drop["unfinished"] += 1
            continue
        if it["think"] and not text.startswith("<think>"):
            text = "<think>\n" + text                                    # template puts <think> in the reply
        if len(tok(it["text"] + text).input_ids) > 6000:
            drop["too_long"] += 1
            continue
        rows.append(dict(id=f"sd-{it['id']}", kind="general", source=it["source"], think=it["think"], prompt=it["prompt"],
                         answer=text, qtype="general", dated=False, order="none"))
    with open(args.out, "w", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r) + "\n")
    print(args.out, len(rows), "rows | dropped", drop, "| think", sum(r["think"] for r in rows),
          "| sha256", hashlib.sha256(open(args.out, "rb").read()).hexdigest()[:16].upper())


if __name__ == "__main__":
    main()
